### ISSUE TITLE
Create a database for trainings for better performance

### ISSUE THREAD

**Issue by IgnacioHeredia** [ai4os/ai4-papi#7]
**If needed**, create a database for trainings (instead of parsing Nomad) for better performance

**Comment by tdviet** [comment]
The database will improve the performance but it may prevent replication of the PAPI for high-availability

**Comment by IgnacioHeredia** [comment]
Anyway, just realized this wouldn't work for trainings because the API cannot know about the status of the deployments without querying Nomad. So even if it managed to save basic deployment info in a database it would still need to query nomad to get the status of the deployments (pending, queued, etc). So any performance gain would be lost.

Therefore closing this issue.
